<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>9.0</LangVersion>

    <!-- SourceGeneratorを動作させるための設定 -->
    <IsRoslynComponent>true</IsRoslynComponent>
    <AnalyzerLanguage>cs</AnalyzerLanguage>

    <!-- NuGet配布用の設定 -->
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <DevelopmentDependency>true</DevelopmentDependency>
    <IncludeSymbols>false</IncludeSymbols>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.3.1" />
    <PackageReference Include="System.Text.Json" Version="10.0.2" />
    <PackageReference Include="YamlDotNet" Version="13.7.1" />
  </ItemGroup>

  <!-- NuGetパッケージの出力先をanalyzers/dotnet/csに -->
  <ItemGroup>
    <None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs"
      Visible="false" />
  </ItemGroup>
</Project>