using System;
using System.Globalization;
using System.IO;
using System.Security.Cryptography;
using System.Text;
using Newtonsoft.Json.Linq;
using UnityEditor;
using UnityEngine;

namespace Rhycol.OpenApiCodeGen.SourceGenerator.Editor
{
    internal sealed class OpenApiClientDefinitionWriter
    {
        internal const string DefinitionFileSuffix = ".OpenApiDefinition.cs";
        internal const string OwnedFileHeader =
            "// <auto-generated by UnityOpenApiCodeGen.SourceGenerator>";
        internal const string ClientIdentityPrefix = "// Client identity SHA-256: ";
        internal const string SpecIdPrefix = "// Spec ID: ";

        private const string RuntimeAssemblyName = "Unity.OpenApiCodeGen.SourceGenerator";
        private const string RuntimeAssemblyGuid = "2734be4203e44073a484476db8e446f3";
        private static readonly Encoding StrictUtf8 = new UTF8Encoding(false, true);

        private readonly string projectRoot;
        private readonly IAtomicFileWriter fileWriter;
        private readonly Action<string> importAsset;

        internal OpenApiClientDefinitionWriter(
            string projectRoot,
            IAtomicFileWriter fileWriter,
            Action<string> importAsset)
        {
            if (string.IsNullOrWhiteSpace(projectRoot))
            {
                throw new ArgumentException("A project root is required.", nameof(projectRoot));
            }

            this.projectRoot = Path.GetFullPath(projectRoot);
            this.fileWriter = fileWriter ?? throw new ArgumentNullException(nameof(fileWriter));
            this.importAsset = importAsset ?? throw new ArgumentNullException(nameof(importAsset));
        }

        internal static OpenApiClientDefinitionWriter CreateForCurrentProject()
        {
            string currentProjectRoot = Directory.GetParent(Application.dataPath).FullName;
            return new OpenApiClientDefinitionWriter(
                currentProjectRoot,
                new AtomicFileWriter(),
                assetPath => AssetDatabase.ImportAsset(
                    assetPath,
                    ImportAssetOptions.ForceSynchronousImport |
                    ImportAssetOptions.ForceUpdate));
        }

        internal OpenApiClientDefinitionPlan Prepare(
            string outputFolderPath,
            string apiName,
            string generatedNamespace)
        {
            if (!CSharpNameValidator.TryValidateIdentifier(apiName, out string apiNameFailure))
            {
                throw new ArgumentException(
                    "API name is invalid: " + apiNameFailure,
                    nameof(apiName));
            }

            if (!CSharpNameValidator.TryValidateNamespace(
                    generatedNamespace,
                    out string namespaceFailure))
            {
                throw new ArgumentException(namespaceFailure, nameof(generatedNamespace));
            }

            string outputFolder = ResolveOutputFolder(outputFolderPath);
            AsmdefInfo targetAssembly = ResolveTargetAssembly(outputFolder);
            string clientIdentity = string.Join(
                "\n",
                targetAssembly.Name,
                generatedNamespace,
                apiName);
            byte[] clientIdentityHash = ComputeSha256(StrictUtf8.GetBytes(clientIdentity));
            string clientIdentitySha256 = ToLowerHex(clientIdentityHash, clientIdentityHash.Length);
            string deterministicSpecId = ToLowerHex(clientIdentityHash, 16);
            string definitionPath = Path.Combine(
                outputFolder,
                apiName + DefinitionFileSuffix);
            string specId = ResolveSpecIdFromExistingOwnedFile(
                definitionPath,
                clientIdentitySha256,
                deterministicSpecId);
            string definitionAssetPath = ToAssetPath(definitionPath);
            byte[] content = StrictUtf8.GetBytes(
                BuildDefinitionSource(
                    specId,
                    clientIdentitySha256,
                    apiName,
                    generatedNamespace));

            return new OpenApiClientDefinitionPlan(
                specId,
                clientIdentitySha256,
                targetAssembly.Name,
                definitionPath,
                definitionAssetPath,
                apiName,
                generatedNamespace,
                content);
        }

        internal bool Publish(OpenApiClientDefinitionPlan plan)
        {
            if (plan == null)
            {
                throw new ArgumentNullException(nameof(plan));
            }

            // Recheck immediately before writing so a file created after Prepare is never
            // treated as ours merely because the earlier path inspection succeeded.
            string currentSpecId = ResolveSpecIdFromExistingOwnedFile(
                plan.DefinitionPath,
                plan.ClientIdentitySha256,
                plan.SpecId);
            if (!string.Equals(currentSpecId, plan.SpecId, StringComparison.Ordinal))
            {
                throw new InvalidOperationException(
                    "The owned definition changed after generation was prepared: " +
                    plan.DefinitionPath);
            }

            if (FileContentEquals(plan.DefinitionPath, plan.Content))
            {
                return false;
            }

            fileWriter.WriteAllBytesAtomically(plan.DefinitionPath, plan.Content);
            importAsset(plan.DefinitionAssetPath);
            return true;
        }

        private string ResolveOutputFolder(string outputFolderPath)
        {
            if (string.IsNullOrWhiteSpace(outputFolderPath))
            {
                throw new ArgumentException(
                    "A definition output folder is required.",
                    nameof(outputFolderPath));
            }

            string fullOutputFolder = Path.IsPathRooted(outputFolderPath)
                ? Path.GetFullPath(outputFolderPath)
                : Path.GetFullPath(Path.Combine(projectRoot, outputFolderPath));
            string assetsRoot = Path.Combine(projectRoot, "Assets");
            if (!IsSameOrDescendant(assetsRoot, fullOutputFolder))
            {
                throw new InvalidOperationException(
                    "The definition output folder must resolve under the project's Assets folder.");
            }

            if (File.Exists(fullOutputFolder))
            {
                throw new InvalidOperationException(
                    "The definition output folder resolves to an existing file.");
            }

            EnsureNoSymbolicLink(assetsRoot, fullOutputFolder);
            return fullOutputFolder;
        }

        private AsmdefInfo ResolveTargetAssembly(string outputFolder)
        {
            string assetsRoot = Path.Combine(projectRoot, "Assets");
            string currentDirectory = outputFolder;

            while (IsSameOrDescendant(assetsRoot, currentDirectory))
            {
                if (Directory.Exists(currentDirectory))
                {
                    string[] asmdefPaths = Directory.GetFiles(
                        currentDirectory,
                        "*.asmdef",
                        SearchOption.TopDirectoryOnly);
                    if (asmdefPaths.Length > 1)
                    {
                        throw new InvalidOperationException(
                            "The definition output folder is under an ambiguous asmdef directory: " +
                            currentDirectory);
                    }

                    if (asmdefPaths.Length == 1)
                    {
                        AsmdefInfo asmdef = ReadAsmdef(asmdefPaths[0]);
                        if (!asmdef.ReferencesSourceGeneratorRuntime)
                        {
                            throw new InvalidOperationException(
                                string.Format(
                                    CultureInfo.InvariantCulture,
                                    "Target asmdef '{0}' must reference '{1}'.",
                                    asmdef.Name,
                                    RuntimeAssemblyName));
                        }

                        return asmdef;
                    }
                }

                if (PathsEqual(currentDirectory, assetsRoot))
                {
                    break;
                }

                DirectoryInfo parent = Directory.GetParent(currentDirectory);
                if (parent == null)
                {
                    break;
                }

                currentDirectory = parent.FullName;
            }

            throw new InvalidOperationException(
                "The definition output folder must be contained by an asmdef that references '" +
                RuntimeAssemblyName + "'.");
        }

        private static AsmdefInfo ReadAsmdef(string asmdefPath)
        {
            JObject document;
            try
            {
                document = JObject.Parse(File.ReadAllText(asmdefPath, StrictUtf8));
            }
            catch (Exception exception) when (
                exception is IOException ||
                exception is UnauthorizedAccessException ||
                exception is Newtonsoft.Json.JsonException)
            {
                throw new InvalidOperationException(
                    "The target asmdef could not be read: " + asmdefPath,
                    exception);
            }

            string name = document.Value<string>("name");
            if (string.IsNullOrWhiteSpace(name))
            {
                throw new InvalidOperationException(
                    "The target asmdef does not declare an assembly name: " + asmdefPath);
            }

            bool referencesRuntime = false;
            JArray references = document["references"] as JArray;
            if (references != null)
            {
                foreach (JToken referenceToken in references)
                {
                    string reference = referenceToken.Type == JTokenType.String
                        ? referenceToken.Value<string>()
                        : string.Empty;
                    if (string.Equals(reference, RuntimeAssemblyName, StringComparison.Ordinal) ||
                        string.Equals(
                            reference,
                            "GUID:" + RuntimeAssemblyGuid,
                            StringComparison.OrdinalIgnoreCase))
                    {
                        referencesRuntime = true;
                        break;
                    }
                }
            }

            return new AsmdefInfo(name, referencesRuntime);
        }

        private static string ResolveSpecIdFromExistingOwnedFile(
            string definitionPath,
            string expectedClientIdentity,
            string fallbackSpecId)
        {
            if (!File.Exists(definitionPath))
            {
                return fallbackSpecId;
            }

            string content;
            try
            {
                content = File.ReadAllText(definitionPath, StrictUtf8);
            }
            catch (Exception exception) when (
                exception is IOException ||
                exception is UnauthorizedAccessException ||
                exception is DecoderFallbackException)
            {
                throw new InvalidOperationException(
                    "The existing definition file could not be inspected: " + definitionPath,
                    exception);
            }

            string normalizedContent = content.Replace("\r\n", "\n");
            if (!normalizedContent.StartsWith(OwnedFileHeader + "\n", StringComparison.Ordinal))
            {
                throw new InvalidOperationException(
                    "Refusing to overwrite a definition file not owned by UnityOpenApiCodeGen: " +
                    definitionPath);
            }

            string existingIdentity = ReadHeaderValue(normalizedContent, ClientIdentityPrefix);
            if (!string.Equals(
                    existingIdentity,
                    expectedClientIdentity,
                    StringComparison.Ordinal))
            {
                throw new InvalidOperationException(
                    "Refusing to overwrite an owned definition for a different client identity: " +
                    definitionPath);
            }

            string existingSpecId = ReadHeaderValue(normalizedContent, SpecIdPrefix);
            Guid parsedSpecId;
            if (!Guid.TryParseExact(existingSpecId, "N", out parsedSpecId) ||
                !string.Equals(
                    parsedSpecId.ToString("N", CultureInfo.InvariantCulture),
                    existingSpecId,
                    StringComparison.Ordinal))
            {
                throw new InvalidOperationException(
                    "The owned definition contains an invalid Spec ID: " + definitionPath);
            }

            return existingSpecId;
        }

        private static string ReadHeaderValue(string content, string prefix)
        {
            using (var reader = new StringReader(content))
            {
                for (int lineIndex = 0; lineIndex < 8; lineIndex++)
                {
                    string line = reader.ReadLine();
                    if (line == null)
                    {
                        break;
                    }

                    if (line.StartsWith(prefix, StringComparison.Ordinal))
                    {
                        return line.Substring(prefix.Length);
                    }
                }
            }

            return string.Empty;
        }

        private static string BuildDefinitionSource(
            string specId,
            string clientIdentitySha256,
            string apiName,
            string generatedNamespace)
        {
            var builder = new StringBuilder();
            builder.AppendLine(OwnedFileHeader);
            builder.Append(ClientIdentityPrefix).AppendLine(clientIdentitySha256);
            builder.Append(SpecIdPrefix).AppendLine(specId);
            builder.AppendLine("// Changes to this file will be replaced by the next Generate operation.");
            builder.AppendLine("#if OPENAPI_CODEGEN_SOURCE_GENERATOR");
            builder.Append("namespace ").Append(generatedNamespace).AppendLine();
            builder.AppendLine("{");
            builder.AppendLine("    [global::Rhycol.OpenApiCodeGen.SourceGenerator.OpenApiClientDefinitionAttribute(");
            builder.Append("        \"").Append(EscapeStringLiteral(specId)).AppendLine("\",");
            builder.Append("        \"").Append(EscapeStringLiteral(apiName)).AppendLine("\",");
            builder.Append("        \"").Append(EscapeStringLiteral(generatedNamespace)).AppendLine("\",");
            builder.AppendLine("        global::Rhycol.OpenApiCodeGen.SourceGenerator.OpenApiDocumentFormat.Json)]");
            builder.Append("    public partial class ").Append(apiName).AppendLine();
            builder.AppendLine("    {");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            builder.AppendLine("#endif");
            return builder.ToString();
        }

        private static string EscapeStringLiteral(string value)
        {
            var builder = new StringBuilder(value.Length);
            for (int index = 0; index < value.Length; index++)
            {
                char character = value[index];
                switch (character)
                {
                    case '\\':
                        builder.Append("\\\\");
                        break;
                    case '"':
                        builder.Append("\\\"");
                        break;
                    case '\n':
                        builder.Append("\\n");
                        break;
                    case '\r':
                        builder.Append("\\r");
                        break;
                    case '\t':
                        builder.Append("\\t");
                        break;
                    default:
                        if (char.IsControl(character) || char.IsSurrogate(character))
                        {
                            builder.Append("\\u");
                            builder.Append(((int)character).ToString("x4", CultureInfo.InvariantCulture));
                        }
                        else
                        {
                            builder.Append(character);
                        }

                        break;
                }
            }

            return builder.ToString();
        }

        private string ToAssetPath(string fullPath)
        {
            string relativePath = fullPath.Substring(projectRoot.Length)
                .TrimStart(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar)
                .Replace('\\', '/');
            return relativePath;
        }

        private static bool FileContentEquals(string path, byte[] expected)
        {
            try
            {
                if (!File.Exists(path))
                {
                    return false;
                }

                byte[] existing = File.ReadAllBytes(path);
                if (existing.Length != expected.Length)
                {
                    return false;
                }

                for (int index = 0; index < existing.Length; index++)
                {
                    if (existing[index] != expected[index])
                    {
                        return false;
                    }
                }

                return true;
            }
            catch (IOException)
            {
                return false;
            }
            catch (UnauthorizedAccessException)
            {
                return false;
            }
        }

        private static byte[] ComputeSha256(byte[] bytes)
        {
            using (SHA256 sha256 = SHA256.Create())
            {
                return sha256.ComputeHash(bytes);
            }
        }

        private static string ToLowerHex(byte[] bytes, int count)
        {
            var builder = new StringBuilder(count * 2);
            for (int index = 0; index < count; index++)
            {
                builder.Append(bytes[index].ToString("x2", CultureInfo.InvariantCulture));
            }

            return builder.ToString();
        }

        private static void EnsureNoSymbolicLink(string assetsRoot, string outputFolder)
        {
            string current = outputFolder;
            while (IsSameOrDescendant(assetsRoot, current))
            {
                if (Directory.Exists(current) &&
                    (File.GetAttributes(current) & FileAttributes.ReparsePoint) != 0)
                {
                    throw new InvalidOperationException(
                        "The definition output path must not traverse a symbolic link: " + current);
                }

                if (PathsEqual(current, assetsRoot))
                {
                    break;
                }

                DirectoryInfo parent = Directory.GetParent(current);
                if (parent == null)
                {
                    break;
                }

                current = parent.FullName;
            }
        }

        private static bool IsSameOrDescendant(string parentPath, string candidatePath)
        {
            string normalizedParent = Path.GetFullPath(parentPath)
                .TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
            string normalizedCandidate = Path.GetFullPath(candidatePath)
                .TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
            if (PathsEqual(normalizedParent, normalizedCandidate))
            {
                return true;
            }

            string parentPrefix = normalizedParent + Path.DirectorySeparatorChar;
            return normalizedCandidate.StartsWith(parentPrefix, PathComparison);
        }

        private static bool PathsEqual(string left, string right)
        {
            return string.Equals(
                Path.GetFullPath(left).TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar),
                Path.GetFullPath(right).TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar),
                PathComparison);
        }

        private static StringComparison PathComparison =>
            Path.DirectorySeparatorChar == '\\'
                ? StringComparison.OrdinalIgnoreCase
                : StringComparison.Ordinal;

        private sealed class AsmdefInfo
        {
            internal AsmdefInfo(string name, bool referencesSourceGeneratorRuntime)
            {
                Name = name;
                ReferencesSourceGeneratorRuntime = referencesSourceGeneratorRuntime;
            }

            internal string Name { get; }

            internal bool ReferencesSourceGeneratorRuntime { get; }
        }
    }
}
