using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Security.Cryptography;
using System.Text;
using Rhycol.OpenApiCodeGen.SourceGenerator;
using Newtonsoft.Json.Linq;
using UnityEditor;
using UnityEngine;

namespace Rhycol.OpenApiCodeGen.SourceGenerator.Editor
{
    internal sealed class OpenApiClientDefinitionWriter
    {
        internal const string DefinitionFileSuffix = ".OpenApiDefinition.cs";
        internal const string OwnedFileHeader =
            "// <auto-generated by UnityOpenApiCodeGen.SourceGenerator>";
        internal const string ClientIdentityPrefix = "// Client identity SHA-256: ";
        internal const string SpecIdPrefix = "// Spec ID: ";

        private const string RuntimeAssemblyName = "Unity.OpenApiCodeGen.SourceGenerator";
        private const string RuntimeAssemblyGuid = "2734be4203e44073a484476db8e446f3";
        private static readonly Encoding StrictUtf8 = new UTF8Encoding(false, true);

        private readonly string projectRoot;
        private readonly IAtomicFileWriter fileWriter;
        private readonly Action<string> importAsset;

        internal OpenApiClientDefinitionWriter(
            string projectRoot,
            IAtomicFileWriter fileWriter,
            Action<string> importAsset)
        {
            if (string.IsNullOrWhiteSpace(projectRoot))
            {
                throw new ArgumentException("A project root is required.", nameof(projectRoot));
            }

            this.projectRoot = Path.GetFullPath(projectRoot);
            this.fileWriter = fileWriter ?? throw new ArgumentNullException(nameof(fileWriter));
            this.importAsset = importAsset ?? throw new ArgumentNullException(nameof(importAsset));
        }

        internal static OpenApiClientDefinitionWriter CreateForCurrentProject()
        {
            string currentProjectRoot = Directory.GetParent(Application.dataPath).FullName;
            return new OpenApiClientDefinitionWriter(
                currentProjectRoot,
                new AtomicFileWriter(),
                assetPath => AssetDatabase.ImportAsset(
                    assetPath,
                    ImportAssetOptions.ForceSynchronousImport |
                    ImportAssetOptions.ForceUpdate));
        }

        internal OpenApiClientDefinitionPlan Prepare(
            string outputFolderPath,
            string apiName,
            string generatedNamespace)
        {
            return Prepare(
                outputFolderPath,
                apiName,
                generatedNamespace,
                OpenApiDocumentFormat.Json);
        }

        internal OpenApiClientDefinitionPlan Prepare(
            string outputFolderPath,
            string apiName,
            string generatedNamespace,
            OpenApiDocumentFormat documentFormat)
        {
            if (documentFormat != OpenApiDocumentFormat.Json &&
                documentFormat != OpenApiDocumentFormat.Yaml)
            {
                throw new ArgumentOutOfRangeException(nameof(documentFormat));
            }

            if (!CSharpNameValidator.TryValidateIdentifier(apiName, out string apiNameFailure))
            {
                throw new ArgumentException(
                    "API name is invalid: " + apiNameFailure,
                    nameof(apiName));
            }

            if (!CSharpNameValidator.TryValidateNamespace(
                    generatedNamespace,
                    out string namespaceFailure))
            {
                throw new ArgumentException(namespaceFailure, nameof(generatedNamespace));
            }

            string outputFolder = ResolveOutputFolder(outputFolderPath);
            AsmdefInfo targetAssembly = ResolveTargetAssembly(outputFolder);
            string clientIdentitySha256 = ComputeClientIdentitySha256(
                targetAssembly.Name,
                generatedNamespace,
                apiName);
            string deterministicSpecId = clientIdentitySha256.Substring(0, 32);
            string definitionPath = Path.Combine(
                outputFolder,
                apiName + DefinitionFileSuffix);
            ExistingDefinitionInfo existingDefinition = InspectExistingDefinition(
                definitionPath,
                targetAssembly.Name,
                apiName,
                generatedNamespace,
                clientIdentitySha256,
                deterministicSpecId);
            string migrationSourcePath = string.Empty;
            if (!existingDefinition.Exists)
            {
                MigrationCandidate candidate = FindMigrationCandidate(
                    targetAssembly,
                    definitionPath,
                    apiName,
                    generatedNamespace,
                    clientIdentitySha256);
                if (candidate != null)
                {
                    migrationSourcePath = candidate.Path;
                    existingDefinition = candidate.Definition;
                    EnsureDefinitionFileIsSafe(definitionPath + ".meta");
                    EnsureDefinitionFileIsSafe(migrationSourcePath + ".meta");
                    if (File.Exists(definitionPath + ".meta"))
                    {
                        throw new SafeGenerationException(
                            "Refusing to migrate an owned definition over an occupied destination metadata file.");
                    }
                }
            }
            string specId = existingDefinition.SpecId;
            string definitionAssetPath = ToAssetPath(definitionPath);
            byte[] content = StrictUtf8.GetBytes(
                BuildDefinitionSource(
                    specId,
                    clientIdentitySha256,
                    apiName,
                    generatedNamespace,
                    documentFormat));

            return new OpenApiClientDefinitionPlan(
                specId,
                clientIdentitySha256,
                targetAssembly.Name,
                definitionPath,
                definitionAssetPath,
                apiName,
                generatedNamespace,
                documentFormat,
                content,
                existingDefinition.Exists && string.IsNullOrEmpty(migrationSourcePath),
                string.IsNullOrEmpty(migrationSourcePath)
                    ? existingDefinition.ContentSha256
                    : string.Empty,
                migrationSourcePath,
                string.IsNullOrEmpty(migrationSourcePath)
                    ? string.Empty
                    : ToAssetPath(migrationSourcePath),
                File.Exists(definitionPath + ".meta"),
                ComputeFileSha256(definitionPath + ".meta"),
                string.IsNullOrEmpty(migrationSourcePath)
                    ? string.Empty
                    : existingDefinition.ContentSha256,
                !string.IsNullOrEmpty(migrationSourcePath) && File.Exists(migrationSourcePath + ".meta"),
                string.IsNullOrEmpty(migrationSourcePath)
                    ? string.Empty
                    : ComputeFileSha256(migrationSourcePath + ".meta"),
                !string.IsNullOrEmpty(migrationSourcePath) && File.Exists(migrationSourcePath + ".meta")
                    ? File.ReadAllBytes(migrationSourcePath + ".meta")
                    : new byte[0]);
        }

        internal bool Publish(OpenApiClientDefinitionPlan plan)
        {
            if (plan == null)
            {
                throw new ArgumentNullException(nameof(plan));
            }

            string outputFolder = ResolveOutputFolder(Path.GetDirectoryName(plan.DefinitionPath));
            AsmdefInfo targetAssembly = ResolveTargetAssembly(outputFolder);
            if (!string.Equals(
                    targetAssembly.Name,
                    plan.TargetAssemblyName,
                    StringComparison.Ordinal))
            {
                throw new InvalidOperationException(
                    "The target assembly changed after generation was prepared.");
            }

            string expectedDefinitionPath = Path.Combine(
                outputFolder,
                plan.ApiName + DefinitionFileSuffix);
            if (!PathsEqual(expectedDefinitionPath, plan.DefinitionPath))
            {
                throw new InvalidOperationException(
                    "The definition path changed after generation was prepared.");
            }

            string expectedIdentity = ComputeClientIdentitySha256(
                targetAssembly.Name,
                plan.GeneratedNamespace,
                plan.ApiName);
            if (!string.Equals(
                    expectedIdentity,
                    plan.ClientIdentitySha256,
                    StringComparison.Ordinal))
            {
                throw new InvalidOperationException(
                    "The client identity changed after generation was prepared.");
            }

            // Recheck the exact bytes immediately before writing. This prevents a definition
            // created, removed, or edited after Prepare from being treated as the inspected file.
            ExistingDefinitionInfo currentDefinition = InspectExistingDefinition(
                plan.DefinitionPath,
                targetAssembly.Name,
                plan.ApiName,
                plan.GeneratedNamespace,
                plan.ClientIdentitySha256,
                plan.SpecId);
            if (currentDefinition.Exists != plan.PreparedDefinitionExists ||
                !string.Equals(
                    currentDefinition.ContentSha256,
                    plan.PreparedDefinitionSha256,
                    StringComparison.Ordinal) ||
                !string.Equals(currentDefinition.SpecId, plan.SpecId, StringComparison.Ordinal))
            {
                throw new InvalidOperationException(
                    "The owned definition changed after generation was prepared: " +
                    plan.DefinitionPath);
            }

            ValidateMigrationState(plan, targetAssembly);

            if (FileContentEquals(plan.DefinitionPath, plan.Content))
            {
                return false;
            }

            if (plan.IsFolderMigration)
            {
                PublishFolderMigration(plan);
            }
            else
            {
                fileWriter.WriteAllBytesAtomically(plan.DefinitionPath, plan.Content);
            }
            importAsset(plan.DefinitionAssetPath);
            return true;
        }

        internal OpenApiClientDefinitionPlan WithDocumentFormat(
            OpenApiClientDefinitionPlan plan,
            OpenApiDocumentFormat documentFormat)
        {
            if (plan == null)
            {
                throw new ArgumentNullException(nameof(plan));
            }

            if (documentFormat != OpenApiDocumentFormat.Json &&
                documentFormat != OpenApiDocumentFormat.Yaml)
            {
                throw new ArgumentOutOfRangeException(nameof(documentFormat));
            }

            if (plan.DocumentFormat == documentFormat)
            {
                return plan;
            }

            byte[] content = StrictUtf8.GetBytes(BuildDefinitionSource(
                plan.SpecId,
                plan.ClientIdentitySha256,
                plan.ApiName,
                plan.GeneratedNamespace,
                documentFormat));
            return new OpenApiClientDefinitionPlan(
                plan.SpecId,
                plan.ClientIdentitySha256,
                plan.TargetAssemblyName,
                plan.DefinitionPath,
                plan.DefinitionAssetPath,
                plan.ApiName,
                plan.GeneratedNamespace,
                documentFormat,
                content,
                plan.PreparedDefinitionExists,
                plan.PreparedDefinitionSha256,
                plan.MigrationSourcePath,
                plan.MigrationSourceAssetPath,
                plan.PreparedDestinationMetaExists,
                plan.PreparedDestinationMetaSha256,
                plan.PreparedMigrationSourceSha256,
                plan.PreparedMigrationSourceMetaExists,
                plan.PreparedMigrationSourceMetaSha256,
                plan.PreparedMigrationSourceMetaBytes);
        }

        internal DefinitionPublication PublishTransactional(OpenApiClientDefinitionPlan plan)
        {
            if (plan == null)
            {
                throw new ArgumentNullException(nameof(plan));
            }

            DefinitionFileSnapshot[] snapshots = CaptureDefinitionSnapshots(plan.DefinitionArtifactPaths);
            try
            {
                bool changed = Publish(plan);
                return new DefinitionPublication(
                    changed,
                    changed
                        ? () => TryRestoreDefinitionSnapshots(plan, snapshots)
                        : EmptyRollback);
            }
            catch
            {
                TryRestoreDefinitionSnapshots(plan, snapshots);
                throw;
            }
        }

        private static DefinitionFileSnapshot[] CaptureDefinitionSnapshots(string[] paths)
        {
            var snapshots = new DefinitionFileSnapshot[paths.Length];
            for (int index = 0; index < paths.Length; index++)
            {
                string path = paths[index];
                EnsureDefinitionFileIsSafe(path);
                snapshots[index] = File.Exists(path)
                    ? new DefinitionFileSnapshot(path, true, File.ReadAllBytes(path))
                    : new DefinitionFileSnapshot(path, false, new byte[0]);
            }

            return snapshots;
        }

        private void TryRestoreDefinitionSnapshots(
            OpenApiClientDefinitionPlan plan,
            DefinitionFileSnapshot[] snapshots)
        {
            try
            {
                FileSnapshotState[] outputs = CaptureExpectedPublishedState(plan, snapshots);
                for (int index = 0; index < snapshots.Length; index++)
                {
                    if (!SnapshotMatches(snapshots[index]) && !SnapshotMatches(outputs[index]))
                    {
                        return;
                    }
                }

                // Remove the destination side first so a migrated .meta GUID never exists at
                // both paths while the original snapshot is restored.
                for (int index = 0; index < snapshots.Length; index++)
                {
                    if (!snapshots[index].Exists && File.Exists(snapshots[index].Path))
                    {
                        File.Delete(snapshots[index].Path);
                    }
                }

                for (int index = 0; index < snapshots.Length; index++)
                {
                    if (snapshots[index].Exists)
                    {
                        fileWriter.WriteAllBytesAtomically(snapshots[index].Path, snapshots[index].Bytes);
                    }
                }

                importAsset(plan.IsFolderMigration
                    ? plan.MigrationSourceAssetPath
                    : plan.DefinitionAssetPath);
            }
            catch (Exception)
            {
                // The cache service owns a second durable snapshot for this path and will
                // restore it even when a definition writer or AssetDatabase operation fails.
            }
        }

        private static void EmptyRollback()
        {
        }

        private void PublishFolderMigration(OpenApiClientDefinitionPlan plan)
        {
            fileWriter.WriteAllBytesAtomically(plan.DefinitionPath, plan.Content);
            File.Delete(plan.MigrationSourcePath);
            if (File.Exists(plan.MigrationSourcePath + ".meta"))
            {
                File.Delete(plan.MigrationSourcePath + ".meta");
            }

            if (plan.PreparedMigrationSourceMetaExists)
            {
                fileWriter.WriteAllBytesAtomically(
                    plan.DefinitionPath + ".meta",
                    plan.PreparedMigrationSourceMetaBytes);
            }
        }

        private void ValidateMigrationState(
            OpenApiClientDefinitionPlan plan,
            AsmdefInfo targetAssembly)
        {
            ValidateFileSnapshot(
                plan.DefinitionPath + ".meta",
                plan.PreparedDestinationMetaExists,
                plan.PreparedDestinationMetaSha256,
                "The destination definition metadata changed after generation was prepared.");
            if (!plan.IsFolderMigration)
            {
                return;
            }

            AsmdefInfo sourceAssembly = ResolveTargetAssembly(
                Path.GetDirectoryName(plan.MigrationSourcePath));
            if (!PathsEqual(sourceAssembly.DirectoryPath, targetAssembly.DirectoryPath))
            {
                throw new InvalidOperationException(
                    "The definition migration source crossed an assembly boundary after generation was prepared.");
            }

            ExistingDefinitionInfo source = InspectExistingDefinition(
                plan.MigrationSourcePath,
                targetAssembly.Name,
                plan.ApiName,
                plan.GeneratedNamespace,
                plan.ClientIdentitySha256,
                plan.SpecId);
            if (!source.Exists ||
                !string.Equals(source.SpecId, plan.SpecId, StringComparison.Ordinal) ||
                !string.Equals(
                    source.ContentSha256,
                    plan.PreparedMigrationSourceSha256,
                    StringComparison.Ordinal))
            {
                throw new InvalidOperationException(
                    "The definition migration source changed after generation was prepared.");
            }

            ValidateFileSnapshot(
                plan.MigrationSourcePath + ".meta",
                plan.PreparedMigrationSourceMetaExists,
                plan.PreparedMigrationSourceMetaSha256,
                "The definition migration source metadata changed after generation was prepared.");

            MigrationCandidate currentCandidate = FindMigrationCandidate(
                targetAssembly,
                plan.DefinitionPath,
                plan.ApiName,
                plan.GeneratedNamespace,
                plan.ClientIdentitySha256);
            if (currentCandidate == null ||
                !PathsEqual(currentCandidate.Path, plan.MigrationSourcePath))
            {
                throw new InvalidOperationException(
                    "The owned definition migration set changed after generation was prepared.");
            }
        }

        private static void ValidateFileSnapshot(
            string path,
            bool expectedExists,
            string expectedSha256,
            string message)
        {
            EnsureDefinitionFileIsSafe(path);
            bool exists = File.Exists(path);
            if (exists != expectedExists ||
                (exists && !string.Equals(
                    ComputeFileSha256(path),
                    expectedSha256,
                    StringComparison.Ordinal)))
            {
                throw new InvalidOperationException(message + " " + path);
            }
        }

        private MigrationCandidate FindMigrationCandidate(
            AsmdefInfo targetAssembly,
            string destinationPath,
            string apiName,
            string generatedNamespace,
            string clientIdentitySha256)
        {
            var matches = new List<MigrationCandidate>();
            bool foundDifferentNamespace = false;
            FindMigrationCandidatesInDirectory(
                targetAssembly.DirectoryPath,
                targetAssembly.DirectoryPath,
                destinationPath,
                targetAssembly.Name,
                apiName,
                generatedNamespace,
                clientIdentitySha256,
                matches,
                ref foundDifferentNamespace);
            if (matches.Count > 1)
            {
                throw new SafeGenerationException(
                    "Multiple owned definitions match this client. Move or remove the duplicates before generating.");
            }

            if (matches.Count == 0 && foundDifferentNamespace)
            {
                throw new SafeGenerationException(
                    "Change the generated namespace at the existing definition location before moving its output folder.");
            }

            return matches.Count == 1 ? matches[0] : null;
        }

        private void FindMigrationCandidatesInDirectory(
            string directory,
            string assemblyRoot,
            string destinationPath,
            string targetAssemblyName,
            string apiName,
            string generatedNamespace,
            string clientIdentitySha256,
            List<MigrationCandidate> matches,
            ref bool foundDifferentNamespace)
        {
            if ((File.GetAttributes(directory) & FileAttributes.ReparsePoint) != 0)
            {
                throw new SafeGenerationException(
                    "The target assembly contains a symbolic-link boundary that prevents safe definition migration: " +
                    directory);
            }

            if (!PathsEqual(directory, assemblyRoot) &&
                (Directory.GetFiles(directory, "*.asmdef", SearchOption.TopDirectoryOnly).Length != 0 ||
                 Directory.GetFiles(directory, "*.asmref", SearchOption.TopDirectoryOnly).Length != 0))
            {
                return;
            }

            string candidatePath = Path.Combine(directory, apiName + DefinitionFileSuffix);
            if (!PathsEqual(candidatePath, destinationPath) && File.Exists(candidatePath))
            {
                EnsureDefinitionFileIsSafe(candidatePath);
                byte[] bytes = File.ReadAllBytes(candidatePath);
                string normalized;
                try
                {
                    normalized = NormalizeLineEndings(StrictUtf8.GetString(bytes));
                }
                catch (DecoderFallbackException exception)
                {
                    throw new InvalidOperationException(
                        "An owned definition candidate is not strict UTF-8: " + candidatePath,
                        exception);
                }

                if (normalized.StartsWith(OwnedFileHeader + "\n", StringComparison.Ordinal))
                {
                    ParsedOwnedDefinition parsed = ParseOwnedDefinitionSource(normalized, candidatePath);
                    if (string.Equals(parsed.ApiName, apiName, StringComparison.Ordinal))
                    {
                        string parsedIdentity = ComputeClientIdentitySha256(
                            targetAssemblyName,
                            parsed.GeneratedNamespace,
                            apiName);
                        ExistingDefinitionInfo inspected = InspectExistingDefinition(
                            candidatePath,
                            targetAssemblyName,
                            apiName,
                            parsed.GeneratedNamespace,
                            parsedIdentity,
                            parsedIdentity.Substring(0, 32));
                        if (string.Equals(
                                parsed.GeneratedNamespace,
                                generatedNamespace,
                                StringComparison.Ordinal) &&
                            string.Equals(
                                parsedIdentity,
                                clientIdentitySha256,
                                StringComparison.Ordinal))
                        {
                            matches.Add(new MigrationCandidate(candidatePath, inspected));
                        }
                        else
                        {
                            foundDifferentNamespace = true;
                        }
                    }
                }
            }

            string[] childDirectories = Directory.GetDirectories(directory);
            Array.Sort(childDirectories, StringComparer.Ordinal);
            for (int index = 0; index < childDirectories.Length; index++)
            {
                FindMigrationCandidatesInDirectory(
                    childDirectories[index],
                    assemblyRoot,
                    destinationPath,
                    targetAssemblyName,
                    apiName,
                    generatedNamespace,
                    clientIdentitySha256,
                    matches,
                    ref foundDifferentNamespace);
            }
        }

        private static FileSnapshotState[] CaptureExpectedPublishedState(
            OpenApiClientDefinitionPlan plan,
            DefinitionFileSnapshot[] snapshots)
        {
            if (!plan.IsFolderMigration)
            {
                return new[]
                {
                    new FileSnapshotState(plan.DefinitionPath, true, plan.Content),
                };
            }

            return new[]
            {
                new FileSnapshotState(plan.DefinitionPath, true, plan.Content),
                new FileSnapshotState(
                    plan.DefinitionPath + ".meta",
                    snapshots[3].Exists,
                    snapshots[3].Bytes),
                new FileSnapshotState(plan.MigrationSourcePath, false, new byte[0]),
                new FileSnapshotState(plan.MigrationSourcePath + ".meta", false, new byte[0]),
            };
        }

        private static bool SnapshotMatches(DefinitionFileSnapshot snapshot)
        {
            return snapshot.Exists
                ? FileContentEquals(snapshot.Path, snapshot.Bytes)
                : !File.Exists(snapshot.Path);
        }

        private static bool SnapshotMatches(FileSnapshotState snapshot)
        {
            return snapshot.Exists
                ? FileContentEquals(snapshot.Path, snapshot.Bytes)
                : !File.Exists(snapshot.Path);
        }

        private string ResolveOutputFolder(string outputFolderPath)
        {
            if (string.IsNullOrWhiteSpace(outputFolderPath))
            {
                throw new ArgumentException(
                    "A definition output folder is required.",
                    nameof(outputFolderPath));
            }

            string fullOutputFolder = Path.IsPathRooted(outputFolderPath)
                ? Path.GetFullPath(outputFolderPath)
                : Path.GetFullPath(Path.Combine(projectRoot, outputFolderPath));
            string assetsRoot = Path.Combine(projectRoot, "Assets");
            if (!IsSameOrDescendant(assetsRoot, fullOutputFolder))
            {
                throw new InvalidOperationException(
                    "The definition output folder must resolve under the project's Assets folder.");
            }

            if (File.Exists(fullOutputFolder))
            {
                throw new InvalidOperationException(
                    "The definition output folder resolves to an existing file.");
            }

            EnsureNoSymbolicLink(assetsRoot, fullOutputFolder);
            return fullOutputFolder;
        }

        private AsmdefInfo ResolveTargetAssembly(string outputFolder)
        {
            string assetsRoot = Path.Combine(projectRoot, "Assets");
            string currentDirectory = outputFolder;

            while (IsSameOrDescendant(assetsRoot, currentDirectory))
            {
                if (Directory.Exists(currentDirectory))
                {
                    string[] asmrefPaths = Directory.GetFiles(
                        currentDirectory,
                        "*.asmref",
                        SearchOption.TopDirectoryOnly);
                    if (asmrefPaths.Length != 0)
                    {
                        throw new InvalidOperationException(
                            "The definition output folder must not cross an asmref boundary: " +
                            currentDirectory);
                    }

                    string[] asmdefPaths = Directory.GetFiles(
                        currentDirectory,
                        "*.asmdef",
                        SearchOption.TopDirectoryOnly);
                    if (asmdefPaths.Length > 1)
                    {
                        throw new InvalidOperationException(
                            "The definition output folder is under an ambiguous asmdef directory: " +
                            currentDirectory);
                    }

                    if (asmdefPaths.Length == 1)
                    {
                        AsmdefInfo asmdef = ReadAsmdef(asmdefPaths[0]);
                        if (!asmdef.ReferencesSourceGeneratorRuntime)
                        {
                            throw new InvalidOperationException(
                                string.Format(
                                    CultureInfo.InvariantCulture,
                                    "Target asmdef '{0}' must reference '{1}'.",
                                    asmdef.Name,
                                    RuntimeAssemblyName));
                        }

                        return asmdef;
                    }
                }

                if (PathsEqual(currentDirectory, assetsRoot))
                {
                    break;
                }

                DirectoryInfo parent = Directory.GetParent(currentDirectory);
                if (parent == null)
                {
                    break;
                }

                currentDirectory = parent.FullName;
            }

            throw new InvalidOperationException(
                "The definition output folder must be contained by an asmdef that references '" +
                RuntimeAssemblyName + "'.");
        }

        private static AsmdefInfo ReadAsmdef(string asmdefPath)
        {
            JObject document;
            try
            {
                document = JObject.Parse(File.ReadAllText(asmdefPath, StrictUtf8));
            }
            catch (Exception exception) when (
                exception is IOException ||
                exception is UnauthorizedAccessException ||
                exception is Newtonsoft.Json.JsonException)
            {
                throw new InvalidOperationException(
                    "The target asmdef could not be read: " + asmdefPath,
                    exception);
            }

            string name = document.Value<string>("name");
            if (string.IsNullOrWhiteSpace(name))
            {
                throw new InvalidOperationException(
                    "The target asmdef does not declare an assembly name: " + asmdefPath);
            }

            bool referencesRuntime = false;
            JArray references = document["references"] as JArray;
            if (references != null)
            {
                foreach (JToken referenceToken in references)
                {
                    string reference = referenceToken.Type == JTokenType.String
                        ? referenceToken.Value<string>()
                        : string.Empty;
                    if (string.Equals(reference, RuntimeAssemblyName, StringComparison.Ordinal) ||
                        string.Equals(
                            reference,
                            "GUID:" + RuntimeAssemblyGuid,
                            StringComparison.OrdinalIgnoreCase))
                    {
                        referencesRuntime = true;
                        break;
                    }
                }
            }

            return new AsmdefInfo(
                name,
                referencesRuntime,
                Path.GetDirectoryName(Path.GetFullPath(asmdefPath)));
        }

        private static ExistingDefinitionInfo InspectExistingDefinition(
            string definitionPath,
            string targetAssemblyName,
            string expectedApiName,
            string expectedGeneratedNamespace,
            string expectedClientIdentity,
            string fallbackSpecId)
        {
            EnsureDefinitionFileIsSafe(definitionPath);
            if (!File.Exists(definitionPath))
            {
                return new ExistingDefinitionInfo(false, fallbackSpecId, string.Empty);
            }

            byte[] bytes;
            string content;
            try
            {
                bytes = File.ReadAllBytes(definitionPath);
                content = StrictUtf8.GetString(bytes);
            }
            catch (Exception exception) when (
                exception is IOException ||
                exception is UnauthorizedAccessException ||
                exception is DecoderFallbackException)
            {
                throw new InvalidOperationException(
                    "The existing definition file could not be inspected: " + definitionPath,
                    exception);
            }

            string normalizedContent = NormalizeLineEndings(content);
            if (!normalizedContent.StartsWith(OwnedFileHeader + "\n", StringComparison.Ordinal))
            {
                throw new SafeGenerationException(
                    "Refusing to overwrite a definition file not owned by UnityOpenApiCodeGen.");
            }

            string existingSpecId = ReadHeaderValue(normalizedContent, SpecIdPrefix);
            Guid parsedSpecId;
            if (!Guid.TryParseExact(existingSpecId, "N", out parsedSpecId) ||
                !string.Equals(
                    parsedSpecId.ToString("N", CultureInfo.InvariantCulture),
                    existingSpecId,
                    StringComparison.Ordinal))
            {
                throw new InvalidOperationException(
                    "The owned definition contains an invalid Spec ID: " + definitionPath);
            }

            ParsedOwnedDefinition parsed = ParseOwnedDefinitionSource(
                normalizedContent,
                definitionPath);
            if (!string.Equals(parsed.SpecId, existingSpecId, StringComparison.Ordinal))
            {
                throw new InvalidOperationException(
                    "The owned definition's header and source declare different Spec IDs: " +
                    definitionPath);
            }

            if (!string.Equals(parsed.ApiName, expectedApiName, StringComparison.Ordinal))
            {
                throw new InvalidOperationException(
                    "Refusing to overwrite an owned definition for a different API name: " +
                    definitionPath);
            }

            string existingIdentity = ReadHeaderValue(normalizedContent, ClientIdentityPrefix);
            string recomputedExistingIdentity = ComputeClientIdentitySha256(
                targetAssemblyName,
                parsed.GeneratedNamespace,
                parsed.ApiName);
            if (!string.Equals(
                    existingIdentity,
                    recomputedExistingIdentity,
                    StringComparison.Ordinal))
            {
                throw new InvalidOperationException(
                    "The owned definition's client identity does not match its generated source: " +
                    definitionPath);
            }

            string expectedSource = NormalizeLineEndings(BuildDefinitionSource(
                existingSpecId,
                existingIdentity,
                parsed.ApiName,
                parsed.GeneratedNamespace,
                parsed.DocumentFormat));
            if (!string.Equals(normalizedContent, expectedSource, StringComparison.Ordinal))
            {
                throw new InvalidOperationException(
                    "The owned definition source was modified outside UnityOpenApiCodeGen: " +
                    definitionPath);
            }

            // A namespace-only change intentionally changes the identity. The target assembly
            // and API name above remain authoritative, so the existing Spec ID can be retained.
            if (string.Equals(existingIdentity, expectedClientIdentity, StringComparison.Ordinal) ||
                !string.Equals(
                    parsed.GeneratedNamespace,
                    expectedGeneratedNamespace,
                    StringComparison.Ordinal))
            {
                return new ExistingDefinitionInfo(
                    true,
                    existingSpecId,
                    ToLowerHex(ComputeSha256(bytes), 32));
            }

            throw new InvalidOperationException(
                "Refusing to overwrite an owned definition for a different client identity: " +
                definitionPath);
        }

        private static ParsedOwnedDefinition ParseOwnedDefinitionSource(
            string normalizedContent,
            string definitionPath)
        {
            string[] lines = normalizedContent.Split('\n');
            int attributeLine = FindUniqueLine(
                lines,
                "    [global::Rhycol.OpenApiCodeGen.SourceGenerator.OpenApiClientDefinitionAttribute(",
                definitionPath);
            if (attributeLine + 4 >= lines.Length)
            {
                throw InvalidOwnedDefinitionSource(definitionPath);
            }

            string specId = ReadQuotedAttributeArgument(lines[attributeLine + 1], true, definitionPath);
            string apiName = ReadQuotedAttributeArgument(lines[attributeLine + 2], true, definitionPath);
            string generatedNamespace = ReadQuotedAttributeArgument(
                lines[attributeLine + 3],
                true,
                definitionPath);
            const string FormatPrefix =
                "        global::Rhycol.OpenApiCodeGen.SourceGenerator.OpenApiDocumentFormat.";
            string formatLine = lines[attributeLine + 4];
            if (!formatLine.StartsWith(FormatPrefix, StringComparison.Ordinal) ||
                !formatLine.EndsWith(")]", StringComparison.Ordinal))
            {
                throw InvalidOwnedDefinitionSource(definitionPath);
            }

            string formatName = formatLine.Substring(
                FormatPrefix.Length,
                formatLine.Length - FormatPrefix.Length - 2);
            OpenApiDocumentFormat documentFormat;
            if (string.Equals(formatName, "Json", StringComparison.Ordinal))
            {
                documentFormat = OpenApiDocumentFormat.Json;
            }
            else if (string.Equals(formatName, "Yaml", StringComparison.Ordinal))
            {
                documentFormat = OpenApiDocumentFormat.Yaml;
            }
            else
            {
                throw InvalidOwnedDefinitionSource(definitionPath);
            }

            int namespaceLine = FindUniqueLine(
                lines,
                "namespace " + generatedNamespace,
                definitionPath);
            int classLine = FindUniqueLine(
                lines,
                "    public partial class " + apiName,
                definitionPath);
            if (namespaceLine >= attributeLine || classLine <= attributeLine ||
                !CSharpNameValidator.TryValidateIdentifier(apiName, out _) ||
                !CSharpNameValidator.TryValidateNamespace(generatedNamespace, out _))
            {
                throw InvalidOwnedDefinitionSource(definitionPath);
            }

            return new ParsedOwnedDefinition(
                specId,
                apiName,
                generatedNamespace,
                documentFormat);
        }

        private static int FindUniqueLine(
            string[] lines,
            string expectedLine,
            string definitionPath)
        {
            int match = -1;
            for (int index = 0; index < lines.Length; index++)
            {
                if (!string.Equals(lines[index], expectedLine, StringComparison.Ordinal))
                {
                    continue;
                }

                if (match >= 0)
                {
                    throw InvalidOwnedDefinitionSource(definitionPath);
                }

                match = index;
            }

            if (match < 0)
            {
                throw InvalidOwnedDefinitionSource(definitionPath);
            }

            return match;
        }

        private static string ReadQuotedAttributeArgument(
            string line,
            bool hasTrailingComma,
            string definitionPath)
        {
            const string Prefix = "        \"";
            string suffix = hasTrailingComma ? "\"," : "\"";
            if (!line.StartsWith(Prefix, StringComparison.Ordinal) ||
                !line.EndsWith(suffix, StringComparison.Ordinal) ||
                line.Length < Prefix.Length + suffix.Length)
            {
                throw InvalidOwnedDefinitionSource(definitionPath);
            }

            return line.Substring(
                Prefix.Length,
                line.Length - Prefix.Length - suffix.Length);
        }

        private static InvalidOperationException InvalidOwnedDefinitionSource(string definitionPath)
        {
            return new InvalidOperationException(
                "The owned definition source is not in a recognized generated format: " +
                definitionPath);
        }

        private static string NormalizeLineEndings(string value)
        {
            return value.Replace("\r\n", "\n").Replace('\r', '\n');
        }

        private static string ComputeClientIdentitySha256(
            string targetAssemblyName,
            string generatedNamespace,
            string apiName)
        {
            string identity = string.Join(
                "\n",
                targetAssemblyName,
                generatedNamespace,
                apiName);
            byte[] hash = ComputeSha256(StrictUtf8.GetBytes(identity));
            return ToLowerHex(hash, hash.Length);
        }

        private static void EnsureDefinitionFileIsSafe(string definitionPath)
        {
            if (Directory.Exists(definitionPath))
            {
                throw new InvalidOperationException(
                    "The definition path resolves to an existing directory.");
            }

            if (File.Exists(definitionPath) &&
                (File.GetAttributes(definitionPath) & FileAttributes.ReparsePoint) != 0)
            {
                throw new InvalidOperationException(
                    "The definition path must not be a symbolic link: " + definitionPath);
            }
        }

        private static string ReadHeaderValue(string content, string prefix)
        {
            using (var reader = new StringReader(content))
            {
                for (int lineIndex = 0; lineIndex < 8; lineIndex++)
                {
                    string line = reader.ReadLine();
                    if (line == null)
                    {
                        break;
                    }

                    if (line.StartsWith(prefix, StringComparison.Ordinal))
                    {
                        return line.Substring(prefix.Length);
                    }
                }
            }

            return string.Empty;
        }

        private static string BuildDefinitionSource(
            string specId,
            string clientIdentitySha256,
            string apiName,
            string generatedNamespace,
            OpenApiDocumentFormat documentFormat)
        {
            var builder = new StringBuilder();
            builder.AppendLine(OwnedFileHeader);
            builder.Append(ClientIdentityPrefix).AppendLine(clientIdentitySha256);
            builder.Append(SpecIdPrefix).AppendLine(specId);
            builder.AppendLine("// Changes to this file will be replaced by the next Generate operation.");
            builder.AppendLine("#if OPENAPI_CODEGEN_SOURCE_GENERATOR");
            builder.Append("namespace ").Append(generatedNamespace).AppendLine();
            builder.AppendLine("{");
            builder.AppendLine("    [global::Rhycol.OpenApiCodeGen.SourceGenerator.OpenApiClientDefinitionAttribute(");
            builder.Append("        \"").Append(EscapeStringLiteral(specId)).AppendLine("\",");
            builder.Append("        \"").Append(EscapeStringLiteral(apiName)).AppendLine("\",");
            builder.Append("        \"").Append(EscapeStringLiteral(generatedNamespace)).AppendLine("\",");
            builder.Append("        global::Rhycol.OpenApiCodeGen.SourceGenerator.OpenApiDocumentFormat.");
            builder.AppendLine(documentFormat == OpenApiDocumentFormat.Yaml ? "Yaml)]" : "Json)]");
            builder.Append("    public partial class ").Append(apiName).AppendLine();
            builder.AppendLine("    {");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            builder.AppendLine("#endif");
            return builder.ToString();
        }

        private static string EscapeStringLiteral(string value)
        {
            var builder = new StringBuilder(value.Length);
            for (int index = 0; index < value.Length; index++)
            {
                char character = value[index];
                switch (character)
                {
                    case '\\':
                        builder.Append("\\\\");
                        break;
                    case '"':
                        builder.Append("\\\"");
                        break;
                    case '\n':
                        builder.Append("\\n");
                        break;
                    case '\r':
                        builder.Append("\\r");
                        break;
                    case '\t':
                        builder.Append("\\t");
                        break;
                    default:
                        if (char.IsControl(character) || char.IsSurrogate(character))
                        {
                            builder.Append("\\u");
                            builder.Append(((int)character).ToString("x4", CultureInfo.InvariantCulture));
                        }
                        else
                        {
                            builder.Append(character);
                        }

                        break;
                }
            }

            return builder.ToString();
        }

        private string ToAssetPath(string fullPath)
        {
            string relativePath = fullPath.Substring(projectRoot.Length)
                .TrimStart(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar)
                .Replace('\\', '/');
            return relativePath;
        }

        private static bool FileContentEquals(string path, byte[] expected)
        {
            try
            {
                if (!File.Exists(path))
                {
                    return false;
                }

                byte[] existing = File.ReadAllBytes(path);
                if (existing.Length != expected.Length)
                {
                    return false;
                }

                for (int index = 0; index < existing.Length; index++)
                {
                    if (existing[index] != expected[index])
                    {
                        return false;
                    }
                }

                return true;
            }
            catch (IOException)
            {
                return false;
            }
            catch (UnauthorizedAccessException)
            {
                return false;
            }
        }

        private static byte[] ComputeSha256(byte[] bytes)
        {
            using (SHA256 sha256 = SHA256.Create())
            {
                return sha256.ComputeHash(bytes);
            }
        }

        private static string ComputeFileSha256(string path)
        {
            return File.Exists(path)
                ? ToLowerHex(ComputeSha256(File.ReadAllBytes(path)), 32)
                : string.Empty;
        }

        private static string ToLowerHex(byte[] bytes, int count)
        {
            var builder = new StringBuilder(count * 2);
            for (int index = 0; index < count; index++)
            {
                builder.Append(bytes[index].ToString("x2", CultureInfo.InvariantCulture));
            }

            return builder.ToString();
        }

        private static void EnsureNoSymbolicLink(string assetsRoot, string outputFolder)
        {
            string current = outputFolder;
            while (IsSameOrDescendant(assetsRoot, current))
            {
                if (Directory.Exists(current) &&
                    (File.GetAttributes(current) & FileAttributes.ReparsePoint) != 0)
                {
                    throw new InvalidOperationException(
                        "The definition output path must not traverse a symbolic link: " + current);
                }

                if (PathsEqual(current, assetsRoot))
                {
                    break;
                }

                DirectoryInfo parent = Directory.GetParent(current);
                if (parent == null)
                {
                    break;
                }

                current = parent.FullName;
            }
        }

        private static bool IsSameOrDescendant(string parentPath, string candidatePath)
        {
            string normalizedParent = Path.GetFullPath(parentPath)
                .TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
            string normalizedCandidate = Path.GetFullPath(candidatePath)
                .TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
            if (PathsEqual(normalizedParent, normalizedCandidate))
            {
                return true;
            }

            string parentPrefix = normalizedParent + Path.DirectorySeparatorChar;
            return normalizedCandidate.StartsWith(parentPrefix, PathComparison);
        }

        private static bool PathsEqual(string left, string right)
        {
            return string.Equals(
                Path.GetFullPath(left).TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar),
                Path.GetFullPath(right).TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar),
                PathComparison);
        }

        private static StringComparison PathComparison =>
            Path.DirectorySeparatorChar == '\\'
                ? StringComparison.OrdinalIgnoreCase
                : StringComparison.Ordinal;

        private sealed class AsmdefInfo
        {
            internal AsmdefInfo(
                string name,
                bool referencesSourceGeneratorRuntime,
                string directoryPath)
            {
                Name = name;
                ReferencesSourceGeneratorRuntime = referencesSourceGeneratorRuntime;
                DirectoryPath = directoryPath;
            }

            internal string Name { get; }

            internal bool ReferencesSourceGeneratorRuntime { get; }

            internal string DirectoryPath { get; }
        }

        private sealed class DefinitionFileSnapshot
        {
            internal DefinitionFileSnapshot(string path, bool exists, byte[] bytes)
            {
                Path = path;
                Exists = exists;
                Bytes = bytes;
            }

            internal string Path { get; }

            internal bool Exists { get; }

            internal byte[] Bytes { get; }
        }

        private sealed class FileSnapshotState
        {
            internal FileSnapshotState(string path, bool exists, byte[] bytes)
            {
                Path = path;
                Exists = exists;
                Bytes = bytes;
            }

            internal string Path { get; }

            internal bool Exists { get; }

            internal byte[] Bytes { get; }
        }

        private sealed class MigrationCandidate
        {
            internal MigrationCandidate(string path, ExistingDefinitionInfo definition)
            {
                Path = path;
                Definition = definition;
            }

            internal string Path { get; }

            internal ExistingDefinitionInfo Definition { get; }
        }

        private sealed class ExistingDefinitionInfo
        {
            internal ExistingDefinitionInfo(bool exists, string specId, string contentSha256)
            {
                Exists = exists;
                SpecId = specId;
                ContentSha256 = contentSha256;
            }

            internal bool Exists { get; }

            internal string SpecId { get; }

            internal string ContentSha256 { get; }
        }

        private sealed class ParsedOwnedDefinition
        {
            internal ParsedOwnedDefinition(
                string specId,
                string apiName,
                string generatedNamespace,
                OpenApiDocumentFormat documentFormat)
            {
                SpecId = specId;
                ApiName = apiName;
                GeneratedNamespace = generatedNamespace;
                DocumentFormat = documentFormat;
            }

            internal string SpecId { get; }

            internal string ApiName { get; }

            internal string GeneratedNamespace { get; }

            internal OpenApiDocumentFormat DocumentFormat { get; }
        }
    }

    internal sealed class DefinitionPublication
    {
        internal DefinitionPublication(bool changed, Action rollback)
        {
            Changed = changed;
            Rollback = rollback ?? throw new ArgumentNullException(nameof(rollback));
        }

        internal bool Changed { get; }

        internal Action Rollback { get; }
    }
}
